# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ax7PowerSpin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ax7PowerSpin
  pod 'Firebase/Messaging'
  pod 'AppsFlyerFramework'
  pod 'FBSDKCoreKit', '17.4.0'
end
